apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.1.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
  name: test-operator.vX.Y.Z
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
      - description: ControlPlane is the Schema for the controlplanes API
        displayName: Control Plane
        kind: ControlPlane
        name: controlplanes.test-operator.openstack.org
        version: v1beta1
  description: Test
  displayName: Test
  icon:
    - base64data: ''
      mediatype: ''
  install:
    spec:
      deployments: null
    strategy: ''
  installModes:
    - type: OwnNamespace
      supported: true
    - type: SingleNamespace
      supported: true
    - type: MultiNamespace
      supported: true
    - type: AllNamespaces
      supported: true
  keywords:
    - Test
  links:
    - name: Test Operator
      url: https://test-operator.domain
  maintainers:
    - email: test@test.com
      name: test
  maturity: alpha
  provider:
    name: Test
  version: 0.0.0
